dino:
    backbone: "dinov3"
    remote_repo_dir: "/home/hpc/v114be/v114be20/dinov3"
    model: "dinov3_vitl16"
    remote_weights: "/hnvme/workspace/v114be20-dinov3/dinov3_vitl16"
vggt:
    backbone: "vggt_omega"
    remote_repo_dir: "/"
    model: "vitl16"
    remote_weights: "/hnvme/workspace/v114be20-dinov3/vggt_omega_1b_512.pt"

bottleneck_dim: 64
output_size: [64, 64]

backbone_arch: "dino"
vggt_feature_source: "patch_embed"
finetune_backbone: false
adapt: false

use_lora: false
vggt_lora_target: "patch_embed"
lora_r: 8
lora_alpha: 8
lora_dropout: 0.1
adapt_target_blocks: ~
adapter_scale: 0.1
adapter_dropout: 0.0
